# -*- coding: utf-8 -*-
"""week4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cvBpB7vpMnKhhhfcN8MWn21hsZlOUMD4

Write a function called stop_at_four that iterates through a list of numbers. Using a while loop, append each number to a new list until the number 4 appears. The function should return the new list.
"""

def stop_at_four(numbers):
    new_list = []
    i = 0
    while i < len(numbers) and numbers[i] != 4:
        new_list.append(numbers[i])
        i += 1
    return new_list

def get_yes_or_no(message):
    valid_input = False
    while not valid_input:
        answer = input(message)
        answer = answer.upper() # convert to upper case
        if answer == 'Y' or answer == 'N':
            valid_input = True
        else:
            print('Please enter Y for yes or N for no.')
    return answer

response = get_yes_or_no('Do you like lima beans? Y)es or N)o: ')
if response == 'Y':
    print('Great! They are very healthy.')
else:
    print('Too bad. If cooked right, they are quite tasty.')

def checkout():
    total = 0
    count = 0
    moreItems = True
    while moreItems:
        price = float(input('Enter price of item (0 when done): '))
        if price != 0:
            count = count + 1
            total = total + price
            print('Subtotal: $', total)
        else:
            moreItems = False
    average = total / count
    print('Total items:', count)
    print('Total $', total)

"""Write a function, sublist, that takes in a list of numbers as the parameter. In the function, use a while loop to return a sublist of the input list. The sublist should contain the same values of the original list up until it reaches the number 5 (it should not contain the number 5)."""

def sublist (list_1):
    i = 0
    sub_2 = []
    while i < len(list_1) and list_1[i] != 5:
        sub_2.append(list_1[i])
        i = i + 1
    return sub_2   

print(sublist([1,2,3,4,5,6,7]))

"""Write a function called check_nums that takes a list as its parameter, and contains a while loop that only stops once the element of the list is the number 7. What is returned is a list of all of the numbers up until it reaches 7."""

def check_nums (list1):
    i = 0
    list2 = []
    while i < len(list1) and list1[i]!= 7:
        list2.append(list1[i])
        i = i+1
    return list2   
print(check_nums([1,2,3,4,5,6,7]))

"""Write a function, sublist, that takes in a list of strings as the parameter. In the function, use a while loop to return a sublist of the input list. The sublist should contain the same values of the original list up until it reaches the string “STOP” (it should not contain the string “STOP”)."""

def sublist(str1):
    i = 0
    list2 = []
    while i < len(str1) and str1[i] != "STOP":
        list2.append(str1[i])
        i = i + 1
    return list2

print(sublist(["hello", "hi", "how", "are", "you", "STOP"]))

"""

Challenge: Write a function called beginning that takes a list as input and contains a while loop that only stops once the element of the list is the string ‘bye’. What is returned is a list that contains up to the first 10 strings, regardless of where the loop stops. (i.e., if it stops on the 32nd element, the first 10 are returned. If “bye” is the 5th element, the first 4 are returned.) If you want to make this even more of a challenge, do this without slicing
"""

def beginning(list1):
    i = 0
    list2 = []
    while i < len(list1) and list1[i] != "bye":
        list2.append(list1[i])
        i = i + 1
        
    if len(list2) > 10:
        return list2[0:10]
    else:
        return list2

print(beginning(["hello","hi","how","are","you","doing","today","bye","goodbye","farewell","see","you","later"]))

"""Write a function, test, that takes in three parameters: a required integer, an optional boolean whose default value is True, and an optional dictionary, called dict1, whose default value is {2:3, 4:5, 6:8}. If the boolean parameter is True, the function should test to see if the integer is a key in the dictionary. The value of that key should then be returned. If the boolean parameter is False, return the boolean value “False”."""

def test(int1, bool1=True, dict1={2:3, 4:5, 6:8}):
    if bool1:
        if int1 in dict1:
            return dict1[int1]
    else:
        return False

"""

Write a function called checkingIfIn that takes three parameters. The first is a required parameter, which should be a string. The second is an optional parameter called direction with a default value of True. The third is an optional parameter called d that has a default value of {'apple': 2, 'pear': 1, 'fruit': 19, 'orange': 5, 'banana': 3, 'grapes': 2, 'watermelon': 7}. Write the function checkingIfIn so that when the second parameter is True, it checks to see if the first parameter is a key in the third parameter; if it is, return True, otherwise return False.

But if the second paramter is False, then the function should check to see if the first parameter is not a key of the third. If it’s not, the function should return True in this case, and if it is, it should return False.
"""

def checkingIfIn (str1, direction=True, d={'apple': 2, 'pear': 1, 'fruit': 19, 'orange': 5, 'banana': 3, 'grapes': 2, 'watermelon': 7}):
    if direction:
        if str1 in d:
            return True
        else:
            return False
    else:
        if str1 not in d:
            return True
        else:
            return False

"""We have provided the function checkingIfIn such that if the first input parameter is in the third, dictionary, input parameter, then the function returns that value, and otherwise, it returns False. Follow the instructions in the active code window for specific variable assignmemts."""

def checkingIfIn(a, direction = True, d = {'apple': 2, 'pear': 1, 'fruit': 19, 'orange': 5, 'banana': 3, 'grapes': 2, 'watermelon': 7}):
    if direction == True:
        if a in d:
            return d[a]
        else:
            return False
    else:
        if a not in d:
            return True
        else:
            return d[a]

# Call the function so that it returns False and assign that function call to the variable c_false
c_false = checkingIfIn('hello')
# Call the fucntion so that it returns True and assign it to the variable c_true
c_true = checkingIfIn('num', direction=False)
# Call the function so that the value of fruit is assigned to the variable fruit_ans
fruit_ans = checkingIfIn('fruit')
# Call the function using the first and third parameter so that the value 8 is assigned to the variable param_check

param_check = checkingIfIn('last',direction=True,d={'last':8})